version: '3.5'

services:
  postgres:
    image: honeur/postgres:9.6-omopcdm-5.3.1
    container_name: postgres
    security_opt:
      - no-new-privileges
    ports:
      - "5444:5432"
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
      - type: volume
        source: shared
        target: /var/lib/postgresql/envfileshared
    restart: always
    networks:
      - feder8-net
    command:
      - /bin/bash
      - -c
      - |
          cp /var/lib/postgresql/envfile/honeur.env /var/lib/postgresql/envfileshared/honeur.env
          docker-entrypoint.sh postgres

networks:
  feder8-net:
    name: feder8-net

volumes:
  pgdata:
    external: true
  shared:
    external: true
