version: '3.5'

services:
  etl:
    image: harbor.honeur.org/etl-rmg/etl:image_tag
    volumes:
      - "./logs:/logs"
      - "data_folder:/data"
    networks:
      - honeur_honeur-net
    environment:
      DB_DBMS: "postgresql"
      DB_SERVER : "postgres"
      DB_PORT: "5432"
      DB_DBNAME: "OHDSI"
      DB_SCHEMA: "omopcdm"
      DB_USER: db_username
      DB_PASSWORD: db_password
      LAST_DATA_EXPORT: date_last_export

networks:
  honeur_honeur-net:
    external:
      name: honeur-net
