version: '3.5'

services:
  etl:
    image: harbor.honeur.org/etl-cav/etl:image_tag
    volumes:
      - "./log:/log"
      - "data_folder:/data"
    networks:
      - honeur-net
    environment:
      DB_DBMS: "postgresql"
      DB_SERVER : "postgres"
      DB_PORT: "5432"
      DB_DBNAME: "OHDSI"
      DB_SCHEMA: db_schema
      DB_USER: db_username
      DB_PASSWORD: db_password
      RELEASE_DATE: date_last_export
      VERBOSITY_LEVEL: verbosity_level
      DELIMITER: source_delimiter
      ENCODING: source_encoding
      ETL_DATE_FORMAT: etl_date_format
      ETL_FILENAME_PATHOLOGYTESTS: file_name_pathology
      ETL_FILENAME_APPOINTMENTS: file_name_appointments
      ETL_FILENAME_TREATMENTS: file_name_treatments
      ETL_FILENAME_PATIENTS: file_name_patients

networks:
  honeur-net:
    external:
      name: feder8-net
