version: '3.5'
services:
  webapi-source-qa-disable:
    container_name: webapi-source-qa-disable
    volumes:
      - ./setup-conf:/postgres/setup-scripts/conf
      - shared-qa:/var/lib/shared
    image: honeur/postgres-webapi-source:disable-qa
    external_links:
      - postgres
    networks:
      - feder8-net
    command:
      - /bin/bash
      - -c
      - |
          source /postgres/setup-scripts/setenv.sh
          python -u source_deletion.py conf/setup.yml

networks:
  feder8-net:
    name: feder8-net
  
volumes:
  shared-qa:
    external: true