version: '3.5'
services:
  postgres-qa:
    image: honeur/postgres
    container_name: postgres-qa
    ports:
      - "5445:5432"
    volumes:
      - pgdata-qa:/var/lib/postgresql/data
      - shared-qa:/var/lib/postgresql/envfileshared
    restart: always
    networks:
      - feder8-net
    command:
      - /bin/sh
      - -c
      - |
          mkdir -p /var/lib/postgresql/envfileshared
          cp /var/lib/postgresql/envfile/honeur.env /var/lib/postgresql/envfileshared/honeur.env
          docker-entrypoint.sh postgres
  webapi-source-qa-enable:
    container_name: webapi-source-qa-enable
    volumes:
      - ./setup-conf:/postgres/setup-scripts/conf
      - shared-qa:/var/lib/shared
    image: honeur/postgres-webapi-source:enable-qa
    external_links:
      - postgres
    depends_on:
      - postgres-qa
    networks:
      - feder8-net
    command:
      - /bin/bash
      - -c
      - |
          source /postgres/setup-scripts/setenv.sh
          python -u source_creation.py conf/setup.yml

networks:
  feder8-net:
    name: feder8-net

volumes:
  pgdata-qa:
    external: true
  shared-qa:
    external: true