docker start postgres
docker start config-server
docker start local-portal
docker start feder8-studio
docker start task-manager
docker start user-mgmt
docker start webapi
docker start atlas
docker start zeppelin
docker start nginx
