version: '3.5'

services:
  etl:
    image: harbor.honeur.org/etl-sourasky/etl:image_tag
    volumes:
      - "./log:/log"
      - "data_folder:/data"
    networks:
      - honeur-net
    environment:
      DB_DBMS: "postgresql"
      DB_SERVER : "postgres"
      DB_PORT: "5432"
      DB_DBNAME: "OHDSI"
      DB_SCHEMA: db_schema
      DB_USER: db_username
      DB_PASSWORD: db_password
      LAST_DATA_EXPORT: date_last_export
      VERBOSITY_LEVEL: verbosity_level
      DELIMITER: source_delimiter
      ETL_DATE_FORMAT: etl_date_format
      ETL_FILENAME_DEMOGRAPHICS: file_name_demographics
      ETL_FILENAME_DISEASE_ADMISSION: file_name_disease_admission
      ETL_FILENAME_DISEASE_AMBULATORY: file_name_disease_ambulatory
      ETL_FILENAME_DISEASE_CHARACTERISTICS_MYELOMA: file_name_disease_char
      ETL_FILENAME_DISEASE_CHRONICDIAGNOSIS: file_name_disease_chronic
      ETL_FILENAME_DISEASE_HEMATODIAGNOSIS: file_name_disease_hema
      ETL_FILENAME_LAB_DATA_CYTOGENETICS: file_name_lab_cytogenetics
      ETL_FILENAME_LAB_DATA_FISH: file_name_lab_fish
      ETL_FILENAME_LAB_DATA_TEST_2010_2015: file_name_lab_test_1015
      ETL_FILENAME_LAB_DATA_TEST_2016_2018: file_name_lab_test_1618
      ETL_FILENAME_LAB_DATA_TEST_2019_2020: file_name_lab_test_1920
      ETL_FILENAME_LAB_DATA_TEST_2021_2022: file_name_lab_test_2122
      ETL_FILENAME_TREATMENT_CATO: file_name_treatment_cato
      ETL_FILENAME_TREATMENT_MAP: file_name_treatment_map
      ETL_FILENAME_TREATMENT_MEDICATION: file_name_treatment_medication
      ETL_ENCODING_DEMOGRAPHICS: encoding_demographics
      ETL_ENCODING_DISEASE_ADMISSION: encoding_disease_admission
      ETL_ENCODING_LAB_DATA_FISH: encoding_lab_fish
      ETL_ENCODING_TREATMENT_CATO: encoding_treatment_cato
      ETL_ENCODING_TREATMENT_MAP: encoding_treatment_map
networks:
  honeur-net:
    external:
      name: feder8-net
